export const CHANGE_CATEGORY_SONG = "SONGS/CATEFORY_SONG";
export const CHANGE_CATEGORY_LIST = "SONGS/CATEGORY_LIST";
export const CHANGE_CURRENT_PAGE = "SONGS/CURRENT_PAGE";
export const CHANGE_CAT = "SONGS/CAT";
