export const CHANGE_CATEGORY_LIST = "DJRADIO/CHANGE_CATEGORY_LIST";
export const CHANGE_CURRENT_ID = "DJRADIO/CHANGE_CURRENT_ID";
export const CHANGE_RECOMMEND = "DJRADIO/CHANGE_RECOMMEND";
export const CHANGE_RANKING = "DJRADIO/CHANGE_RANKING";
export const CHANGE_PAGE = "DJRADIO/CHANGE_DJRADIO";
