export const CHANGE_CURRENT_SONG = "PLAYER/CHANGE_CURRENT_SONG";
export const CHANGE_CURRENT_SEQENCE = "PLAYER/CHANGE_CURRENT_SEQENCE";
export const CHANGE_CURRENT_SONG_INDEX = "PLAYER/CHANGE_CURRENT_SONG_INDEX";
export const CHANGE_PLAYLIST = "PLAYER/PLAYLIST";
export const CHANGE_LYRICLIST = "PLAYER/LYRICLIST";
export const CHANGE_LYRIC_INDEX = "PLAYER/LYRIC_INDEX";
export const CHANGE_TRANSLATE_Y = "PLAYER/TRANSLATE_Y";
export const CLEAR_PLAYLIST = "CLEAR/PLAYLIST";
