export const CHANGE_HOT_RECOMMEND = "RECOMMEND/CHANGE_HOT_RECOMMEND";
export const CHANGE_TOP_BANNERS = "RECOMMEND/CHANGE_TOP_BANNERS";
export const CHANGE_NEW_ALBUM = "RECOMMEND/CHANGE_NEW_ALBUM";
export const CHANGE_UP_RANKING = "CHANGE_UP_RANKING";
export const CHANGE_NEW_RANKING = "CHANGE_NEW_RANKING";
export const CHANGE_ORIGIN_RANKING = "CHANGE_ORIGIN_RANKING";
